import os
import re

file_path = r'd:\C_Drive_Transfer\bron\src\renderer\components\AgentSidebar.tsx'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Define the new buttons block
new_buttons = """                      <div className="flex items-center gap-2">
                         <span className="text-[10px] text-slate-400 font-bold uppercase tracking-tighter mr-1">Export Result</span>
                         
                         {/* PDF/Print */}
                         <button 
                           onClick={() => {
                             const win = window.open('', '_blank');
                             if (!win) {
                               alert('Please allow popups to export to PDF/Print.');
                               return;
                             }
                             let inTable = false;
                             let tableRowIdx = 0;
                             const htmlContent = msg.content
                               .split('\\n')
                               .map(line => {
                                 const t = line.trim();
                                 if (t.startsWith('|')) {
                                   const cells = t.split('|').slice(1, -1).map(c => c.trim());
                                   if (t.includes('---')) return '';
                                   const isHeader = !inTable;
                                   inTable = true;
                                   const res = `<tr style="${isHeader ? 'background-color: #2a4365; color: white; font-weight: bold;' : (tableRowIdx % 2 === 0 ? 'background-color: #f8fafc;' : 'background-color: #ffffff;')}">
                                     ${cells.map(c => `<td style="border: 1px solid #e2e8f0; padding: 12px;">${c}</td>`).join('')}
                                   </tr>`;
                                   tableRowIdx++;
                                   return res;
                                 } else {
                                   if (inTable) { inTable = false; tableRowIdx = 0; }
                                   if (t.startsWith('###')) return `<h3>${t.replace(/^#{3,}\\s*/, '')}</h3>`;
                                   if (t.startsWith('##')) return `<h2>${t.replace(/^#{2}\\s*/, '')}</h2>`;
                                   if (t.startsWith('#')) return `<h1>${t.replace(/^#\s*/, '')}</h1>`;
                                   if (t === '') return '<br/>';
                                   return `<p>${line}</p>`;
                                 }
                               })
                               .join('\\n')
                               .replace(/(<tr[\\s\\S]*?<\\/tr>)+/g, match => `<table style="border-collapse: collapse; width: 100%; margin: 20px 0; border: 1px solid #e2e8f0;">${match}</table>`);

                             win.document.write(`
                               <html>
                                 <head>
                                   <title>Bron Research Report</title>
                                   <style>
                                     body { font-family: -apple-system, sans-serif; padding: 50px; line-height: 1.6; color: #1e293b; max-width: 900px; margin: 0 auto; }
                                     .header { border-bottom: 4px solid #3b82f6; margin-bottom: 40px; padding-bottom: 20px; }
                                     .footer { margin-top: 60px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #64748b; text-align: center; }
                                     table { border-collapse: collapse; width: 100%; margin: 30px 0; font-size: 13px; }
                                     th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; }
                                     h1 { font-size: 32px; color: #0f172a; margin-bottom: 0.5em; }
                                     h2 { font-size: 24px; color: #0f172a; border-bottom: 1px solid #f1f5f9; padding-bottom: 8px; margin-top: 1.5em; }
                                     p { margin-bottom: 1.2em; font-size: 15px; }
                                   </style>
                                 </head>
                                 <body>
                                   <div class="header">
                                     <h1 style="margin:0; color:#3b82f6;">Research Report</h1>
                                     <p style="margin:8px 0 0; font-size:14px; color:#64748b; font-weight: bold;">GENERATED ON ${new Date().toLocaleString()}</p>
                                   </div>
                                   <div id="content">${htmlContent}</div>
                                   <div class="footer">Report generated by Bron Agentic Browser</div>
                                   <script>setTimeout(() => { window.print(); window.close(); }, 1000);</script>
                                 </body>
                               </html>
                             `);
                             win.document.close();
                           }}
                           className="p-1.5 rounded-lg bg-white border border-slate-200 text-slate-500 hover:bg-slate-100 transition-all shadow-sm"
                           title="Export to PDF / Print"
                         >
                           <FileText className="w-3.5 h-3.5" />
                         </button>

                         {/* Word Export */}
                         <button 
                           onClick={() => {
                             let inTable = false;
                             let tableRowIdx = 0;
                             const htmlContent = msg.content
                               .split('\\n')
                               .map(line => {
                                 const t = line.trim();
                                 if (t.startsWith('|')) {
                                   const cells = t.split('|').slice(1, -1).map(c => c.trim());
                                   if (t.includes('---')) return '';
                                   const isHeader = !inTable;
                                   inTable = true;
                                   const res = `<tr style="${isHeader ? 'background-color: #2a4365; color: white; font-weight: bold;' : (tableRowIdx % 2 === 0 ? 'background-color: #f8fafc;' : 'background-color: #ffffff;')}">
                                     ${cells.map(c => `<td style="border: 1px solid #ddd; padding: 10px;">${c}</td>`).join('')}
                                   </tr>`;
                                   tableRowIdx++;
                                   return res;
                                 } else {
                                   if (inTable) { inTable = false; tableRowIdx = 0; }
                                   if (t.startsWith('###')) return `<h3>${t.replace(/^#{3,}\\s*/, '')}</h3>`;
                                   if (t.startsWith('##')) return `<h2>${t.replace(/^#{2}\\s*/, '')}</h2>`;
                                   if (t.startsWith('#')) return `<h1>${t.replace(/^#\s*/, '')}</h1>`;
                                   if (t === '') return '<br/>';
                                   return `<p>${line}</p>`;
                                 }
                               })
                               .join('\\n')
                               .replace(/(<tr[\\s\\S]*?<\\/tr>)+/g, match => `<table style="border-collapse: collapse; width: 100%; margin: 20px 0;">${match}</table>`);

                             const fullDocHtml = `
                               <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
                                 <head><meta charset='utf-8'></head>
                                 <body style="font-family: Arial, sans-serif;">
                                   ${htmlContent}
                                 </body>
                               </html>
                             `;
                             const blob = new Blob(['\\ufeff', fullDocHtml], { type: 'application/msword' });
                             const url = URL.createObjectURL(blob);
                             const link = document.createElement('a');
                             link.href = url;
                             link.download = `Bron_Report_${new Date().getTime()}.doc`;
                             document.body.appendChild(link);
                             link.click();
                             document.body.removeChild(link);
                             URL.revokeObjectURL(url);
                           }}
                           className="p-1.5 rounded-lg bg-white border border-slate-200 text-slate-500 hover:bg-slate-100 transition-all shadow-sm"
                           title="Export to Word"
                         >
                           <Download className="w-3.5 h-3.5" />
                         </button>

                         <button 
                           onClick={() => {
                             navigator.clipboard.writeText(msg.content);
                           }}
                           className="p-1.5 rounded-lg bg-white border border-slate-200 text-slate-500 hover:bg-slate-100 transition-all shadow-sm"
                           title="Copy Raw Markdown"
                         >
                           <Copy className="w-3.5 h-3.5" />
                         </button>
                         <button 
                           onClick={() => {
                              setInput('Continue');
                              handleRun('Continue');
                           }}
                           className="p-1.5 rounded-lg bg-bron-accent/10 border border-bron-accent/20 text-bron-accent hover:bg-bron-accent/20 transition-all shadow-sm ml-1"
                           title="Continue Task"
                         >
                           <RotateCcw className="w-3.5 h-3.5" />
                         </button>
                      </div>"""

# Search for the start and end of the export block
pattern = re.compile(r'<div className="flex items-center gap-2">\\s*<span className="text-\\[10px\\] text-slate-400 font-bold uppercase tracking-tighter mr-1">Export Result</span>.*?<RotateCcw className="w-3.5 h-3.5" />\\s*</button>\\s*</div>', re.DOTALL)

if not pattern.search(content):
    # Fallback to a broader search if the span text changed
    pattern = re.compile(r'<div className="flex items-center gap-2">.*?Export Result.*?<RotateCcw className="w-3.5 h-3.5" />\\s*</button>\\s*</div>', re.DOTALL)

new_content = pattern.sub(new_buttons, content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(new_content)
